# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/ekusa0"

[social.params]
icon = "brand-github"

[[social]]
identifier = "x"
name = "X"
url = "https://x.com/ekusa0"

[social.params]
icon = "brand-x"

[[social]]
identifier = "mastodon"
name = "Mastodon"
url = "https://mastodon.social/@ekusa"

[social.params]
icon = "brand-mastodon"
